### ISSUE TITLE
Create requirements.txt

### ISSUE THREAD

**Issue by surreal30** [surreal30/Food-Data-Scrapper#2]
From `README.md` create a `requirements.txt` to easily manage packages.

**Comment by cleobnvntra** [comment]
Hello @surreal30 ! I would like to work on this issue. Could you please assign this to me? I can get it done asap.
And if possible could you please add the `hacktoberfest` label? Thank you! :)

**Comment by surreal30** [comment]
Sure. Assigning it you. 

Tip: I use UV as my packet and project manager. So, you might want to look into it as well. :)

**Comment by surreal30** [comment]
Closed and merged in PR #3
